```{r outtabfunc, cache=cacheon}
survfunc <- function(time, event, eventname) {
  out <- data.frame(matrix(NA, ncol = 5, nrow = 3))

  out[1, 1] <- eventname
  colnames(out) <- c("Outcome", "Model", levels(edata$valve2))

  ## incidence rate
  out[1, 2] <- "Incidence"

  ev <- edata %>%
    filter(survpop) %>%
    group_by(valve2) %>%
    summarise(
      ev = sum(!!sym(event) == 1),
      .groups = "rowwise"
    )

  s <- edata %>%
    filter(survpop) %>%
    group_by(valve2) %>%
    summarise(
      s = sum(!!sym(time) / 365.25),
      .groups = "rowwise"
    )
  r <- pois.exact(x = ev$ev, pt = s$s / 100)

  out[1, 3:5] <- paste0(
    ev$ev, ", ",
    fn(s$s, dig = 0), ", ",
    fn(r$rate, dig = 1), " (",
    fn(r$lower, dig = 1), "-",
    fn(r$upper, dig = 1), ")"
  )

  # cox regressions

  ## crude

  out[2, 2] <- "Crude HR (95% CI), p-value"

  mod <- coxph(formula(paste0("Surv(", time, ",", event, "== 1) ~ relevel(valve2, ref = 'No VHD')")),
    data = edata %>% filter(survpop)
  )
  smod <- summary(mod)

  out[2, 3:5] <- c(
    "ref",
    paste0(
    fn(smod$conf.int[1:2, "exp(coef)"], dig = 2),
    " (", fn(smod$conf.int[1:2, "lower .95"], dig = 2),
    "-", fn(smod$conf.int[1:2, "upper .95"], dig = 2), "), ",
    fn(smod$coef[1:2, "Pr(>|z|)"], dig = 3, p = TRUE)
  ))

  ## adjusted individual covariates

  out[3, 2] <- "Adjusted HR (95% CI), p-value"

  amod <- with(impsurv, coxph(formula(paste0(
    "Surv(", time, ",", event, " == 1) ~ relevel(valve2, ref = 'No VHD') + ", paste(modvars, collapse = " + ")
  ))))

  ## df the number of events minus the regression coefficients.
  ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
  asmod <- summary(pool(amod,
    dfcom =
      (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
  ))

  out[3, 3:5] <- c(
    "ref", 
    paste0(
    fn(exp(asmod$estimate[1:2]), dig = 2),
    " (", fn(exp(asmod$estimate[1:2] - global_z05 * asmod$std.error[1:2]), dig = 2),
    "-", fn(exp(asmod$estimate[1:2] + global_z05 * asmod$std.error[1:2]), dig = 2), "), ",
    fn(asmod$p.value[1:2], dig = 3, p = TRUE)
  ))
  return(out)
}
```

```{r outtab, cache=cacheon, dependson="outtabfunc"}
out1 <- survfunc(
  time = "outtime_hosphf",
  event = "out_deathcvhosphf",
  eventname = "CV mortality/First HFH"
)
out2 <- survfunc(
  time = "outtime_hosphf",
  event = "out_deathhosphf",
  eventname = "All-cause mortality/First HFH"
)
out3 <- survfunc(
  time = "outtime_death",
  event = "out_deathcv",
  eventname = "CV mortality"
)
out4 <- survfunc(
  time = "outtime_death",
  event = "out_deathnoncv",
  eventname = "Non-CV mortality"
)
out5 <- survfunc(
  time = "outtime_death",
  event = "out_death",
  eventname = "All-cause mortality"
)
out6 <- survfunc(
  time = "outtime_hosphf",
  event = "out_hosphf",
  eventname = "First HFH"
)
out7 <- survfunc(
  time = "outtime_hosp",
  event = "out_hosp",
  eventname = "First all-cause hospitalization"
)

outall <- rbind(
  out1, out2, out3, out4, out5, out6, out7
)

write.xlsx(outall, paste0("./output/tabs/Outcomes by Valve disease_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

footnote(
  default_kable(outall,
    font_size = 6,
    caption = "Outcomes by Valve disease"
  ),
  general = c(
    "Incidence =  no events, sum py, rate/100py (95% CI)."
  )
)
```
